/*
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 *
 * Copyright 1997-2010 Oracle and/or its affiliates. All rights reserved.
 *
 * Oracle and Java are registered trademarks of Oracle and/or its affiliates.
 * Other names may be trademarks of their respective owners.
 *
 * The contents of this file are subject to the terms of either the GNU
 * General Public License Version 2 only ("GPL") or the Common
 * Development and Distribution License("CDDL") (collectively, the
 * "License"). You may not use this file except in compliance with the
 * License. You can obtain a copy of the License at
 * http://www.netbeans.org/cddl-gplv2.html
 * or nbbuild/licenses/CDDL-GPL-2-CP. See the License for the
 * specific language governing permissions and limitations under the
 * License.  When distributing the software, include this License Header
 * Notice in each file and include the License file at
 * nbbuild/licenses/CDDL-GPL-2-CP.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the GPL Version 2 section of the License file that
 * accompanied this code. If applicable, add the following below the
 * License Header, with the fields enclosed by brackets [] replaced by
 * your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * If you wish your version of this file to be governed by only the CDDL
 * or only the GPL Version 2, indicate your decision by adding
 * "[Contributor] elects to include this software in this distribution
 * under the [CDDL or GPL Version 2] license." If you do not indicate a
 * single choice of license, a recipient has the option to distribute
 * your version of this file under either the CDDL, the GPL Version 2 or
 * to extend the choice of license to its licensees as provided above.
 * However, if you add GPL Version 2 code and therefore, elected the GPL
 * Version 2 license, then the option applies only if the new code is
 * made subject to such option by the copyright holder.
 *
 * Contributor(s):
 *
 * Portions Copyrighted 2008 Sun Microsystems, Inc.
 */

package ancestris.modules.gedcom.decesmatchidio;

import genj.util.Registry;
import java.util.List;
import java.util.logging.Logger;

/**
 *
 * @author fabs
 */
public class SearchPanel extends javax.swing.JPanel {

    private final static Logger LOG = Logger.getLogger(SearchPanel.class.getName(), null);

    private DecesMatchId decesMatchId = null;
    private List<DecesMatchId> decesMatchIds = null;

    // Register to save window position
    private Registry registry = null;

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        registry = Registry.get(getClass());

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        legalNameLabel = new javax.swing.JLabel();
        legalNameField = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        sexComboBox = new javax.swing.JComboBox<>();
        birthDateLabel = new javax.swing.JLabel();
        birthDateField = new javax.swing.JTextField();
        birthCityLabel = new javax.swing.JLabel();
        birthCityField = new javax.swing.JTextField();
        birthLocationCodeLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        birthLocationCodeField = new javax.swing.JTextField();
        birthPostalCodeLabel = new javax.swing.JLabel();
        birthPostalCodeField = new javax.swing.JTextField();
        birthDepartmentLabel = new javax.swing.JLabel();
        birthDepartmentField = new javax.swing.JTextField();
        birthCountryLabel = new javax.swing.JLabel();
        birthCountryField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deathDateField = new javax.swing.JTextField();
        deathDepartmentField = new javax.swing.JTextField();
        deathCityLabel = new javax.swing.JLabel();
        deathCountryLabel = new javax.swing.JLabel();
        deathCityField = new javax.swing.JTextField();
        deathCountryField = new javax.swing.JTextField();
        deathLocationCodeLabel = new javax.swing.JLabel();
        deathLocationCodeField = new javax.swing.JTextField();
        deathPostalCodeLabel = new javax.swing.JLabel();
        deathPostalCodeField = new javax.swing.JTextField();
        deathDateLabel = new javax.swing.JLabel();
        deathDepartmentLabel = new javax.swing.JLabel();
        lastSeenAliveLabel = new javax.swing.JLabel();
        lastSeenAliveField = new javax.swing.JTextField();
        fuzzySearchCheckBox = new javax.swing.JCheckBox();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        decesMatchIdsTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        org.openide.awt.Mnemonics.setLocalizedText(lastNameLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.lastNameLabel.text")); // NOI18N

        lastNameField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.lastNameField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(firstNameLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.firstNameLabel.text")); // NOI18N

        firstNameField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.firstNameField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(legalNameLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.legalNameLabel.text")); // NOI18N

        legalNameField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.legalNameField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sexLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.sexLabel.text")); // NOI18N

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "H", "M" }));

        org.openide.awt.Mnemonics.setLocalizedText(birthDateLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthDateLabel.text")); // NOI18N

        birthDateField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthDateField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(birthCityLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthCityLabel.text")); // NOI18N

        birthCityField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthCityField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(birthLocationCodeLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthLocationCodeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.jLabel1.text")); // NOI18N

        birthLocationCodeField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthLocationCodeField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(birthPostalCodeLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthPostalCodeLabel.text")); // NOI18N

        birthPostalCodeField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthPostalCodeField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(birthDepartmentLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthDepartmentLabel.text")); // NOI18N

        birthDepartmentField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthDepartmentField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(birthCountryLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthCountryLabel.text")); // NOI18N

        birthCountryField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.birthCountryField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.jLabel2.text")); // NOI18N

        deathDateField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathDateField.text")); // NOI18N

        deathDepartmentField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathDepartmentField.text")); // NOI18N
        deathDepartmentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deathDepartmentFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(deathCityLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathCityLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deathCountryLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathCountryLabel.text")); // NOI18N

        deathCityField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathCityField.text")); // NOI18N

        deathCountryField
                .setText(org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathCountryField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deathLocationCodeLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathLocationCodeLabel.text")); // NOI18N

        deathLocationCodeField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathLocationCodeField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deathPostalCodeLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathPostalCodeLabel.text")); // NOI18N

        deathPostalCodeField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathPostalCodeField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deathDateLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathDateLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(deathDepartmentLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.deathDepartmentLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lastSeenAliveLabel,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.lastSeenAliveLabel.text")); // NOI18N

        lastSeenAliveField.setText(
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.lastSeenAliveField.text")); // NOI18N
        lastSeenAliveField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastSeenAliveFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(fuzzySearchCheckBox,
                org.openide.util.NbBundle.getMessage(SearchPanel.class, "SearchPanel.fuzzySearchCheckBox.text")); // NOI18N
        fuzzySearchCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuzzySearchCheckBoxActionPerformed(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle
                .getBundle("ancestris/modules/gedcom/decesmatchidio/Bundle"); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(searchButton, bundle.getString("SearchPanel.searchButton.text")); // NOI18N
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        decesMatchIdsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Firstname", "Lastname", "Birth Date", "Birth Location", "Death Date", "Death Location"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        decesMatchIdsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(decesMatchIdsTable);
        if (decesMatchIdsTable.getColumnModel().getColumnCount() > 0) {
            decesMatchIdsTable.getColumnModel().getColumn(0).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(0)
                    .setHeaderValue(bundle.getString("SearchPanel.decesMatchIdsTable.columnModel.title0")); // NOI18N
            decesMatchIdsTable.getColumnModel().getColumn(1).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(1)
                    .setHeaderValue(bundle.getString("SearchPanel.decesMatchIdsTable.columnModel.title1")); // NOI18N
            decesMatchIdsTable.getColumnModel().getColumn(2).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(2)
                    .setHeaderValue(bundle.getString("SearchPanel.decesMatchIdsTable.columnModel.title2")); // NOI18N
            decesMatchIdsTable.getColumnModel().getColumn(3).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle
                    .getMessage(SearchPanel.class, "SearchPanel.decesMatchIdsTable.columnModel.title3")); // NOI18N
            decesMatchIdsTable.getColumnModel().getColumn(4).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(4).setHeaderValue(org.openide.util.NbBundle
                    .getMessage(SearchPanel.class, "SearchPanel.decesMatchIdsTable.columnModel.title4")); // NOI18N
            decesMatchIdsTable.getColumnModel().getColumn(5).setResizable(false);
            decesMatchIdsTable.getColumnModel().getColumn(5).setHeaderValue(org.openide.util.NbBundle
                    .getMessage(SearchPanel.class, "SearchPanel.decesMatchIdsTable.columnModel.title5")); // NOI18N
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                        Short.MAX_VALUE)
                                                .addGap(1, 1, 1))
                                        .addComponent(searchButton)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(lastSeenAliveLabel)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lastSeenAliveField,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 86,
                                                                        Short.MAX_VALUE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(deathLocationCodeLabel)
                                                                                .addComponent(deathDateLabel)
                                                                                .addComponent(deathDepartmentLabel))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(deathDateField,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        101, Short.MAX_VALUE)
                                                                                .addComponent(deathLocationCodeField)
                                                                                .addComponent(deathDepartmentField)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                layout.createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addComponent(
                                                                                                                                lastNameLabel)
                                                                                                                        .addComponent(
                                                                                                                                birthDateLabel))
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        birthLocationCodeLabel)
                                                                                                                .addGap(21,
                                                                                                                        21,
                                                                                                                        21)))
                                                                                                .addComponent(
                                                                                                        birthDepartmentLabel))
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(firstNameLabel)
                                                                                        .addGap(18, 18, 18)))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(firstNameField,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        100, Short.MAX_VALUE)
                                                                                .addComponent(lastNameField,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(birthDateField,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(birthLocationCodeField,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(birthDepartmentField)))))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(legalNameLabel)
                                                                        .addComponent(sexLabel)
                                                                        .addComponent(birthCityLabel)
                                                                        .addComponent(birthPostalCodeLabel)
                                                                        .addComponent(birthCountryLabel)
                                                                        .addComponent(deathCityLabel))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(birthPostalCodeField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addComponent(sexComboBox,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(legalNameField,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        100, Short.MAX_VALUE)
                                                                                .addComponent(birthCityField))
                                                                        .addComponent(birthCountryField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(deathCityField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(deathPostalCodeField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(deathCountryField,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                100,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(deathPostalCodeLabel)
                                                        .addComponent(deathCountryLabel)
                                                        .addComponent(fuzzySearchCheckBox))))
                                .addGap(22, 22, 22)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(legalNameLabel)
                                        .addComponent(legalNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameLabel)
                                        .addComponent(sexLabel)
                                        .addComponent(sexComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthDateLabel)
                                        .addComponent(birthDateField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birthCityLabel)
                                        .addComponent(birthCityField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(birthLocationCodeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(birthLocationCodeLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(birthPostalCodeLabel)
                                                .addComponent(birthPostalCodeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(birthDepartmentLabel)
                                        .addComponent(birthDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(birthCountryLabel)
                                        .addComponent(birthCountryField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deathDateLabel)
                                        .addComponent(deathDateField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deathCityLabel)
                                        .addComponent(deathCityField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(deathLocationCodeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(deathLocationCodeLabel))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(deathPostalCodeLabel)
                                                .addComponent(deathPostalCodeField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deathDepartmentLabel)
                                        .addComponent(deathDepartmentField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deathCountryLabel)
                                        .addComponent(deathCountryField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastSeenAliveLabel)
                                        .addComponent(lastSeenAliveField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fuzzySearchCheckBox))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void deathDepartmentFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deathDepartmentFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_deathDepartmentFieldActionPerformed

    private void lastSeenAliveFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lastSeenAliveFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_lastSeenAliveFieldActionPerformed

    private void fuzzySearchCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_fuzzySearchCheckBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_fuzzySearchCheckBoxActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_SearchButtonActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_SearchButtonMouseClicked
        this.decesMatchIds = DecesMatchIdClient.lookup(this.get());
        final javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) decesMatchIdsTable
                .getModel();
        model.getDataVector().removeAllElements();
        for (DecesMatchId decesMatchId : this.decesMatchIds) {
            Object[] data = {
                    decesMatchId.getFirstName(),
                    decesMatchId.getLastName(),
                    decesMatchId.getBirthDate(),
                    decesMatchId.getBirthCity() + decesMatchId.getBirthPostalCode(),
                    decesMatchId.getDeathDate(),
                    decesMatchId.getDeathCity() + decesMatchId.getDeathPostalCode()
            };
            model.addRow(data);
        }
        model.fireTableDataChanged();
        return;
    }// GEN-LAST:event_SearchButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthCityField;
    private javax.swing.JLabel birthCityLabel;
    private javax.swing.JTextField birthCountryField;
    private javax.swing.JLabel birthCountryLabel;
    private javax.swing.JTextField birthDateField;
    private javax.swing.JLabel birthDateLabel;
    private javax.swing.JTextField birthDepartmentField;
    private javax.swing.JLabel birthDepartmentLabel;
    private javax.swing.JTextField birthLocationCodeField;
    private javax.swing.JLabel birthLocationCodeLabel;
    private javax.swing.JTextField birthPostalCodeField;
    private javax.swing.JLabel birthPostalCodeLabel;
    private javax.swing.JTextField deathCityField;
    private javax.swing.JLabel deathCityLabel;
    private javax.swing.JTextField deathCountryField;
    private javax.swing.JLabel deathCountryLabel;
    private javax.swing.JTextField deathDateField;
    private javax.swing.JLabel deathDateLabel;
    private javax.swing.JTextField deathDepartmentField;
    private javax.swing.JLabel deathDepartmentLabel;
    private javax.swing.JTextField deathLocationCodeField;
    private javax.swing.JLabel deathLocationCodeLabel;
    private javax.swing.JTextField deathPostalCodeField;
    private javax.swing.JLabel deathPostalCodeLabel;
    private javax.swing.JTable decesMatchIdsTable;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JCheckBox fuzzySearchCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastSeenAliveField;
    private javax.swing.JLabel lastSeenAliveLabel;
    private javax.swing.JTextField legalNameField;
    private javax.swing.JLabel legalNameLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel sexLabel;
    // End of variables declaration//GEN-END:variables

    private String getTextFieldValue(javax.swing.JTextField textField) {
        String text = textField.getText();
        if (text != null && text.trim().isEmpty()) {
            return null;
        } else if (text != null) {
            return text.trim(); // Return trimmed text if not empty
        }
        return null;
    }

    public DecesMatchId get() {
        this.decesMatchId.setFirstName(getTextFieldValue(firstNameField));
        this.decesMatchId.setLastName(getTextFieldValue(lastNameField));
        this.decesMatchId.setLegalName(getTextFieldValue(legalNameField));
        switch (sexComboBox.getSelectedItem().toString()) {
            case "F": {
                this.decesMatchId.setSex(Sex.F);
                break;
            }
            case "H": {
                this.decesMatchId.setSex(Sex.H);
                break;
            }
            case "M": {
                this.decesMatchId.setSex(Sex.M);
                break;
            }
        }
        this.decesMatchId.setBirthDate(getTextFieldValue(birthDateField));
        this.decesMatchId.setBirthCity(getTextFieldValue(birthCityField));
        this.decesMatchId.setBirthLocationCode(getTextFieldValue(birthLocationCodeField));
        this.decesMatchId.setBirthPostalCode(getTextFieldValue(birthPostalCodeField));
        this.decesMatchId.setBirthDepartment(getTextFieldValue(birthDepartmentField));
        this.decesMatchId.setBirthCountry(getTextFieldValue(birthCountryField));
        this.decesMatchId.setDeathDate(getTextFieldValue(deathDateField));
        this.decesMatchId.setDeathCity(getTextFieldValue(deathCityField));
        this.decesMatchId.setDeathLocationCode(getTextFieldValue(deathLocationCodeField));
        this.decesMatchId.setDeathPostalCode(getTextFieldValue(deathPostalCodeField));
        this.decesMatchId.setDeathDepartment(getTextFieldValue(deathDepartmentField));
        this.decesMatchId.setDeathCountry(getTextFieldValue(deathCountryField));
        this.decesMatchId.setLastSeenAliveDate(getTextFieldValue(lastSeenAliveField));
        this.decesMatchId.setFuzzy(fuzzySearchCheckBox.isSelected());
        return this.decesMatchId;
    }

    /**
     * @param decesMatchId
     */
    public void set(DecesMatchId decesMatchId) {
        this.decesMatchId = decesMatchId;
        firstNameField.setText(this.decesMatchId.getFirstName());
        lastNameField.setText(this.decesMatchId.getLastName());
        legalNameField.setText(this.decesMatchId.getLegalName());
        sexComboBox.setSelectedItem(this.decesMatchId.getSex().toString());
        birthDateField.setText(this.decesMatchId.getBirthDate());
        birthCityField.setText(this.decesMatchId.getBirthCity());
        birthLocationCodeField.setText(this.decesMatchId.getBirthLocationCode());
        birthPostalCodeField.setText(this.decesMatchId.getBirthPostalCode());
        birthDepartmentField.setText(this.decesMatchId.getBirthDepartment());
        birthCountryField.setText(this.decesMatchId.getBirthCountry());
        deathDateField.setText(this.decesMatchId.getDeathDate());
        deathCityField.setText(this.decesMatchId.getDeathCity());
        deathLocationCodeField.setText(this.decesMatchId.getDeathLocationCode());
        deathPostalCodeField.setText(this.decesMatchId.getDeathPostalCode());
        deathDepartmentField.setText(this.decesMatchId.getDeathDepartment());
        deathCountryField.setText(this.decesMatchId.getDeathCountry());
        lastSeenAliveField.setText(this.decesMatchId.getLastSeenAliveDate());
        fuzzySearchCheckBox.setSelected(this.decesMatchId.isFuzzy());
        final javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) decesMatchIdsTable
                .getModel();
        model.getDataVector().removeAllElements();
    }

    public DecesMatchId getSelected() {
        final int selectedViewRow = decesMatchIdsTable.getSelectedRow();
        if (selectedViewRow < 0 || this.decesMatchIds == null) {
            return null;
        }
        return this.decesMatchIds.get(selectedViewRow);
    }
}
