/*
 * Ancestris - http://www.ancestris.org
 * 
 * Copyright 2014 Ancestris
 * 
 * Author: Fabien Carrion.
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 */
package ancestris.modules.gedcom.decesmatchidio;

import genj.io.FileAssociation;
import java.net.MalformedURLException;
import java.net.URL;
import org.openide.util.Exceptions;

final class DecesMatchIdPanel extends javax.swing.JPanel {

    private final DecesMatchIdOptionsPanelController controller;

    DecesMatchIdPanel(DecesMatchIdOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtApiKey = new javax.swing.JTextField();
        jButtonCreateDecesMatchIdAccount = new javax.swing.JButton();
        jExplanation = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1,
                org.openide.util.NbBundle.getMessage(DecesMatchIdPanel.class, "DecesMatchIdPanel.jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(152, 19));

        jtApiKey.setColumns(20);
        jtApiKey.setText(
                org.openide.util.NbBundle.getMessage(DecesMatchIdPanel.class, "DecesMatchIdPanel.jtApiKey.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButtonCreateDecesMatchIdAccount, org.openide.util.NbBundle
                .getMessage(DecesMatchIdPanel.class, "DecesMatchIdPanel.jButtonCreateDecesMatchIdAccount.text")); // NOI18N
        jButtonCreateDecesMatchIdAccount.setToolTipText(org.openide.util.NbBundle.getMessage(DecesMatchIdPanel.class,
                "DecesMatchIdPanel.jButtonCreateDecesMatchIdAccount.toolTipText")); // NOI18N
        jButtonCreateDecesMatchIdAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateDecesMatchIdAccountActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jExplanation,
                org.openide.util.NbBundle.getMessage(DecesMatchIdPanel.class, "DecesMatchIdPanel.jExplanation.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jExplanation)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jtApiKey, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonCreateDecesMatchIdAccount)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtApiKey, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonCreateDecesMatchIdAccount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jExplanation, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreateDecesMatchIdAccountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonCreateDecesMatchIdAccountActionPerformed
        try {
            FileAssociation.getDefault().execute(new URL("https://deces.matchid.io/search"));
        } catch (MalformedURLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }// GEN-LAST:event_jButtonCreateDecesMatchIdAccountActionPerformed

    void load() {
        jtApiKey.setText(DecesMatchIdOptions.getInstance().getApiKey());
    }

    void store() {
        DecesMatchIdOptions.getInstance().setApiKey(jtApiKey.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateDecesMatchIdAccount;
    private javax.swing.JLabel jExplanation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtApiKey;
    // End of variables declaration//GEN-END:variables
}
